### ISSUE TITLE
feat: customizable githooks directory per repository

### ISSUE THREAD

**Issue by LoeschMaximilian** [gabyx/Githooks#112]
At work we have a convention to use `.git-hooks` as the directory-name for checked in git hooks.
This feature would ease our transition to Githooks away from other solutions.

I saw that `.githooks` is hard-coded, but i lack the go skills to change that myself.

**Comment by gabyx** [comment]
I understand. Maybe you can fork it, and change the following:
Its a good point, maybe we could customize this somehow. But I d like not to go over the git config as this seams a bit overkill. 

You could however (beware of Windows crap and symlinks) introduce a simple relative symlink `.githooks -> .git-hooks` and commit it. Git will work with that fine. On Linux/macOS on Windows too if you enable creation of symlinks

**Comment by gabyx** [comment]
There is a PR which would do this change:
https://github.com/gabyx/Githooks/pull/117

Not sure however about merging this. I have to think. We another simple test for this code such that it works...

**Comment by LoeschMaximilian** [comment]
Thanks, keep up the good work.

**Comment by LoeschMaximilian** [comment]
Thank you very much :)
