### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by gabyx** [gabyx/Githooks#16]
@rycus86 : Do you have time for installing and testing the current version `v1.0.23`.
I tested now a while with updating and sorts on Linux/Windows. on macOs I have not yet tested really, but should work without any problems... :see_no_evil:

**Comment by gabyx** [comment]
Note: The  Dialog Tool is active and will be triggered if you interact with Git over a GUI (VS Code, etc.)...

**Comment by rycus86** [comment]
@gabyx I can try on one or to repos probably. Can I install it for individual repos separately (e.g. not globally)?
Also, is there anything different from the Shell version I should know, or does it work the same when I have the hook scripts inside the repo with the same naming scheme as before?

**Comment by gabyx** [comment]
Nameing scheme is the same (+ some more stuff). Old layout should work out of the box.
Do you want to have the old githooks maintained at the same time when testing the new one? I think its not a good Idea :-)...
Installing for individual repos can be done with `git hooks install` which only installs run-wrappers. 
I think although `cli install` (aka git hooks install) installs only run-wrappers into individual repos, you probably get warnings that install dir is not found if you dont install globally. So best is to really 
You can of course install it globally (maybe with `--prefix`, to not remove your old installation) and apply `git hooks install` inside a repo to enable it.

Or what scenario do you have in mind?

**Comment by rycus86** [comment]
Yep, that should work, thanks!
I do want to keep the old installation, but I have some containers I can try this in I think where it shouldn't be a problem.

**Comment by gabyx** [comment]
Jeah, or test it in the `.devcontainer` with Visual Studio Code... which is pretty nice...

That thing should work too: https://github.com/gabyx/githooks#no-installation

**Comment by gabyx** [comment]
Ah, that reminds me of another problem: The GUI prompt which will be launched if no tty is available from the `runner`,  needs another 
setting probably: `githooks.runnerPromptNonInteractive = true` and probably `githooks.acceptDefaultAnswer = true` or so if git invocation is in inside a docker container in the background, otherwise it will stall...
This part is kind of tricky and I have not yet thought about it, how to make it disable the GUI fallback. But there needs to be a setting to disable GUI fallback, because mostly on a server or so this is not wanted...

**Comment by gabyx** [comment]
So to note here is:
NonInteractive Runner mostly needs
- no GUI prompts (certainly not)
- default answering all prompts if enabled
- disabled auto-update (or at least default answering, which will pass through the updater...)

resulting in no stall at a prompt...

**Comment by rycus86** [comment]
> @rycus86 : I removed the "pre-release" note.
> So 1.0.26 will be the first version. Could you kindly make a note/link on your repo to this new successor? Thanks alot.

Sure, see https://github.com/rycus86/githooks/commit/8ab988c529b71ba012f7ad8d09bc9d1dad8e5b2f :)

**Comment by gabyx** [comment]
perfect, thanks, so you keep your project maintained? Do you intend to make the go port the successor once in a while? I think bug fixing is easier nebertheless its more code ;)
Just interessted what your plans are? :) 

Von meinem iPhone gesendet

**Comment by rycus86** [comment]
I intend to keep it around and maybe fix up minor things here and there if needed, but don't really have any plans for new features at this point. I think it's great to give people the option to choose the Go port if the advanced features is what they're after.
