### ISSUE TITLE
v3 Does not install; Arch Linux

### ISSUE THREAD

**Issue by nf-brentsaner** [gabyx/Githooks#167]
```bash
$ ./install.sh 
! ERROR: Linux Distro '/etc/os-release' not supported currently: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo
```

Arch uses a rolling release. Is there a particular reason `get_platform_os()` is even called in the installer other than to determine the OS? I don't see the OS release/version itself used anywhere for Linux.

How can I install v3, being that Arch has no version (and outright fails the if/else in the installer)?

Note that this same issue would present for other users of rolling distros (Fedora Rawhide, SuSE Tumbleweed, etc.).

**Comment by gabyx** [comment]
@: Can you check that it works on this branch:
#168 by doing
```shell
curl -sL https://github.com/gabyx/Githooks/blob/d5cefdb1902a807c159ee64de06eeb5c90e02dad/scripts/install.sh ...
```
instead

**Comment by gabyx** [comment]
Fixed in: #168

**Comment by nf-brentsaner** [comment]
Will check/confirm in about an hour or so! Apologies for the delay. Thanks for the prompt response/reaction!

**Comment by nf-brentsaner** [comment]
And confirmed on Arch! Thanks again!
