### ISSUE TITLE
Access GIT_ env vars?

### ISSUE THREAD

**Issue by johnnybubonic** [gabyx/Githooks#88]
To ensure consistent behaviour/cross-compat with "vanilla" git hooks, ideally the [GIT_ env vars](https://git-scm.com/book/en/v2/Git-Internals-Environment-Variables) would be recreated or exported where possible.

Relatedly, since I can't use `GIT_WORK_TREE` in a pre-commit now, is the `PWD` env var *guaranteed* to always be the work tree for non-bare repositories?

EDIT: Excellent work, to be clear. This is a much-needed tool. :)

**Comment by gabyx** [comment]
Hi, @johnnybubonic, thanks for the kudos ;) much apprciated.

And sorry for the really late reply.

I thought that we replicate the  whole environment it gets from `git` when executing hooks.
So Githooks does not change it, merely adds some defined values see in the Readme.md
I should add a test. 

The `pwd` is always the repository, we rely on this! (also in bare repos its the repository).

**Comment by johnnybubonic** [comment]
I can absolutely work with PWD/CWD, especially if it's used internally. Thank you! Closing.

**Comment by gabyx** [comment]
I would not rely on `PWD` beeing set. Use `$(pwd)` instead. Probably you meant this.
